### PR TITLE
README: Add Communication section with Forum information

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
Dear maintainers,
As a part of the [Consolidating Ansible discussion platforms initiative](https://forum.ansible.com/t/proposal-consolidating-ansible-discussion-platforms/6812), this PR adds the communication section template defined by the community to the README. Similar PRs are being raised across all included collections under the ansible-collection org for now.

If you have other tags/forum groups related to the collection I didn't spot, please update corresponding lines by suggesting changes to the PR.

IMPORTANT: please, consider moving your WG mentioned in README to the forum group, request it using https://docs.ansible.com/ansible/devel/community/communication.html#requesting-a-forum-group and update the README (or let me know)

##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME
README.md

### CODE REVIEW

**Review by bardielle — APPROVED** [review]

**Comment by bardielle** [comment]
cc @mikemorency

**Comment by Andersson007** [comment]
@bardielle thanks for the fast review!
See the description point about moving WG to the forum. The wiki format for WGs is considered deprecated.
Though it's on maintainers to keep using wikis, but look at one the forum groups as an example https://forum.ansible.com/g/PostgreSQLTeam + it allows to set auto-subscription to associated tags.
So please consider [requesting](https://docs.ansible.com/ansible/devel/community/communication.html#requesting-a-forum-group) a forum group

**Comment by mikemorency** [comment]
I put in a request for the new working group. Ill update the documentation in the following days. Thanks for the help @Andersson007 !

**Comment by Andersson007** [comment]
thanks folks, it's always a pleasure to work with the *vmware community!

**Pull request merged**
