### PR TITLE
Testing with the new version of ansible-core 2.17

### PR DESCRIPTION
**Pull request by bardielle**
##### SUMMARY
Update the sanity test to run with the new ansible-core version 2.17

### CODE REVIEW

**Review by machacekondra — APPROVED** [review]

**Review by mariolenz — APPROVED** [review]
LGTM

**Review by alinabuzachis — APPROVED** [review]

**Comment by alinabuzachis** [comment]
@bardielle If you plan to release soon, you should also remove any support for ansible-core <2.14 since it has reached EOL. I would also remove it from the CI and update meta/runtime.yml and README to say that we are requiring ansible-core > 2.15 for this collection.

**Comment by bardielle** [comment]
@alinabuzachis Thank I will update it.
This change should sign with `minor_changes` or `breaking_changes` ?

**Comment by mariolenz** [comment]
Not to put too fine a point on this, but this collection is part of the Ansible community package (which is a good thing!). Therefor I'd like to suggest synchronizing major releases with this package.

Yes, dropping support for ansible-core 2.14 _is_ a breaking change and requires a new major release. But Ansible 10.0.0 will be released soon and we already have a feature freeze. So we won't be able to get `vmware.vmware_rest 4.0.0` into Ansible 10.

Please, _please_ try to synchronize with the community package. The current stable release 9.x doesn't ship with the current release of this collection, because it's a major release and has been released shortly after Ansible 9.0.0. If you do a new major release, people using the community package will be stuck with an older version.

A good time to have a new major release would be October since Ansible 11 beta will probably have a feature freeze in November. Please consider this when doing major releases.

**Comment by bardielle** [comment]
@mariolenz  I think it's fine to release v4.0.0 on October- November.
I just want to be sure that it's fine to keep the support of 2.14 even if it was EOL. 
@alisonlhart what do you think?

**Comment by alisonlhart** [comment]
Tagging in @chynasan so she can take a look

**Comment by bardielle** [comment]
I asked @EmilyBock and she suggested splitting it into 2 releases
It is important to support the new version so we can release a minor release that includes that and later (in October/ November)  we can release a major version 
cc @alinabuzachis  @mariolenz @alisonlhart 


Shortly I will split this PR into 2 PRs

**Comment by bardielle** [comment]
recheck

**Comment by bardielle** [comment]
@alinabuzachis I see that all the new PRs failing with the same dependency error 

```
ERROR! Failed to resolve the requested dependencies map. Got the candidate cloud.common:5.0.0 (dependency of vmware.vmware_rest:4.0.0) which didn't satisfy all of the following requirements:
* cloud.common:5.0.0
* cloud.common:>=3.0.0,<4.0.0
Hint: Pre-releases hosted on Galaxy or Automation Hub are not installed by default unless a specific version is requested. To enable pre-releases globally, use --pre.
Starting galaxy collection install process
Process install dependency map
```


And in the galaxy.yml there is a dependency  `  cloud.common: ">=3.0.0,<4.0.0"`    what is the reason for that? how can I solve it?

**Comment by alinabuzachis** [comment]
> @alinabuzachis I see that all the new PRs failing with the same dependency error
> 
> ```
> ERROR! Failed to resolve the requested dependencies map. Got the candidate cloud.common:5.0.0 (dependency of vmware.vmware_rest:4.0.0) which didn't satisfy all of the following requirements:
> * cloud.common:5.0.0
> * cloud.common:>=3.0.0,<4.0.0
> Hint: Pre-releases hosted on Galaxy or Automation Hub are not installed by default unless a specific version is requested. To enable pre-releases globally, use --pre.
> Starting galaxy collection install process
> Process install dependency map
> ```
> 
> And in the galaxy.yml there is a dependency ` cloud.common: ">=3.0.0,<4.0.0"` what is the reason for that? how can I solve it?

I created this PR https://github.com/ansible-collections/vmware.vmware_rest/pull/496. We have released cloud.common 4.0.0 last week and the dependency version in the galaxy.yml file needs to be increased.

**Comment by bardielle** [comment]
@alinabuzachis thank you I wasn't aware.

**Review by mikemorency — APPROVED** [review]

**Comment by mariolenz** [comment]
recheck

**Comment by bardielle** [comment]
recheck

**Pull request merged**
