### PR TITLE
Sanity tests: copy ignore-2.13.txt to ignore-2.14.txt

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
https://github.com/ansible-collections/news-for-maintainers/issues/13

Dear maintainers,

I'd like to ask you to track the news-for-maintainers themselves in the future if possible

Thanks!

### CODE REVIEW

**Comment by Andersson007** [comment]
there are unrelated failings, could anyone from maintainers take a look? Thanks

**Comment by Akasurde** [comment]
@Andersson007 Thanks for the PR. Black related errors is fixed via https://github.com/ansible-collections/vmware.vmware_rest/pull/314

**Comment by Andersson007** [comment]
@Akasurde thanks for the quick response!

**Comment by jillr** [comment]
recheck

**Comment by jillr** [comment]
Resolved in 317 - sorry for the lag @Andersson007!

**Comment by Andersson007** [comment]
Thank you!

**Pull request closed without merging**
