### PR TITLE
[DNM] 20231104 Re-generate modules with ansible.content_builder

### PR DESCRIPTION
**Pull request by mariolenz**
This is a test, DO NOT MERGE!

```
pip install black==22.3.0 jsonschema jinja2==3.0.3 boto3 baron redbaron ruamel.yaml autoflake
ansible-galaxy collection install git+https://github.com/ansible-community/ansible.content_builder.git
git clone https://github.com/mariolenz/vmware.vmware_rest.git
mkdir -p /collections/ansible_collections/vmware/vmware_rest/tests
cp -r vmware.vmware_rest/tests/sanity /collections/ansible_collections/vmware/vmware_rest/tests
ansible-playbook build.yaml -e manifest_file=MANIFEST.yaml
autoflake --in-place --remove-all-unused-imports /collections/ansible_collections/vmware/vmware_rest/plugins/modules/*.py
cd vmware.vmware_rest/
git checkout -b 20231104-test-ansible.content_builder
rm -rf plugins/modules/
cp -r /collections/ansible_collections/vmware/vmware_rest/plugins/modules/ plugins/
echo -e '---\nminor_changes:\n- "Re-generate modules with ansible.content_builder."' > changelogs/fragments/regenerate_modules.yaml
git add --all
git commit -m "20231104 Re-generate modules with ansible.content_builder"
git push --set-upstream origin 20231104-test-ansible.content_builder
```

build.yaml:
```
---
- hosts: localhost
  gather_facts: yes
  roles:
    - ansible.content_builder.run
```

MANIFEST.yaml:
```
---
collection:
  path: /collections/ansible_collections/vmware/vmware_rest
  namespace: vmware
  name: vmware_rest
plugins:
  - type: module_openapi
    name: "vmware_rest"
    content: cloud
    api_object_path: vmware.vmware_rest/config/api_specifications/7.0.2
    resource: vmware.vmware_rest/config
    action: generate_all
    unique_key: ""
    rm_swagger_json: ""
    module_version: "1.0.0"
    author: "Ansible Cloud Team"
```

### CODE REVIEW

**Comment by mariolenz** [comment]
@alinabuzachis @GomathiselviS I've already mentioned this in #432:

```
ERROR: Found 2 validate-modules issue(s) which need to be resolved:
ERROR: plugins/modules/vcenter_vm_hardware_adapter_sata.py:0:0: doc-default-does-not-match-spec: Argument 'bus' in argument_spec defines default as (0) but documentation defines default as (None)
ERROR: plugins/modules/vcenter_vm_hardware_adapter_scsi.py:0:0: doc-default-does-not-match-spec: Argument 'bus' in argument_spec defines default as (0) but documentation defines default as (None)
```

Is this a bug in the code generator?

**Comment by mariolenz** [comment]
recheck

**Comment by mariolenz** [comment]
> @alinabuzachis @GomathiselviS I've already mentioned this in #432:
> 
> ```
> ERROR: Found 2 validate-modules issue(s) which need to be resolved:
> ERROR: plugins/modules/vcenter_vm_hardware_adapter_sata.py:0:0: doc-default-does-not-match-spec: Argument 'bus' in argument_spec defines default as (0) but documentation defines default as (None)
> ERROR: plugins/modules/vcenter_vm_hardware_adapter_scsi.py:0:0: doc-default-does-not-match-spec: Argument 'bus' in argument_spec defines default as (0) but documentation defines default as (None)
> ```
> 
> Is this a bug in the code generator?

@alinabuzachis @GomathiselviS Additionally `ansible-tox-linters`fails. Did I do something wrong when re-creating the modules, is this a Zuul issue or a bug in ansible.content_builder?

**Comment by mariolenz** [comment]
> @alinabuzachis @GomathiselviS Additionally `ansible-tox-linters`fails. Did I do something wrong when re-creating the modules, is this a Zuul issue or a bug in ansible.content_builder?

FYI the GHA linting workflow fails also :-/

**Comment by GomathiselviS** [comment]
> > @alinabuzachis @GomathiselviS Additionally `ansible-tox-linters`fails. Did I do something wrong when re-creating the modules, is this a Zuul issue or a bug in ansible.content_builder?
> 
> FYI the GHA linting workflow fails also :-/

It appears that there's a discrepancy between the version of Black used by the content_generator tool and the one employed by the collection. I'll investigate this.

**Comment by mariolenz** [comment]
> It appears that there's a discrepancy between the version of Black used by the content_generator tool and the one employed by the collection. I'll investigate this.

I've installed `black==22.3.0` according to your [documentation](https://github.com/ansible-collections/vmware.vmware_rest/blob/79e8a98d9cafa0f62b4c675b6b1b640d4f62ad8b/development.md#installation).

However, the content_generator seems to use the latest version. Not 22.3.0:

https://github.com/ansible-community/ansible.content_builder/blob/1e706b48b7a1d825d464b697c43355f77cb24fb4/requirements.txt#L1

Should I try again with `pip install black` instead of `pip install black==22.3.0`? Or do you think the problem is somewhere else?

**Comment by mariolenz** [comment]
> Should I try again with `pip install black` instead of `pip install black==22.3.0`?

Nope, this didn't help: #436 :cry:

`pip install black==19.10b0 click==8.0.2` instead of `pip install black==22.3.0` seems to work, though: #437

Maybe because of:

https://github.com/ansible-collections/vmware.vmware_rest/blob/79e8a98d9cafa0f62b4c675b6b1b640d4f62ad8b/tox.ini#L60-L63

:shrug:

**Pull request closed without merging**
