### PR TITLE
Various lookup plugins: Fix docs fields

### PR DESCRIPTION
**Pull request by mariolenz**
##### SUMMARY
I think the author should be `Alina Buzachis (@alinabuzachis)`, not `Alina Buzachis <@alinabuzachis>`.

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
plugins/lookup/cluster_moid.py
plugins/lookup/datacenter_moid.py
plugins/lookup/datastore_moid.py
plugins/lookup/folder_moid.py
plugins/lookup/host_moid.py
plugins/lookup/network_moid.py
plugins/lookup/resource_pool_moid.py
plugins/lookup/vm_moid.py

##### ADDITIONAL INFORMATION
[Documentation fields](https://docs.ansible.com/ansible/latest/dev_guide/developing_modules_documenting.html#documentation-fields)

### CODE REVIEW

**Comment by mariolenz** [comment]
recheck

**Comment by alinabuzachis** [comment]
@mariolenz That's one lookup plugin example we have in amazon.aws https://github.com/ansible-collections/amazon.aws/blob/main/plugins/lookup/aws_ssm.py

```
name: aws_ssm
author:
  - Bill Wang (!UNKNOWN) <ozbillwang(at)gmail.com>
```

**Comment by alinabuzachis** [comment]
And this I the PR that solved the listing issues https://github.com/ansible-collections/amazon.aws/pull/701/files

**Comment by mariolenz** [comment]
@Akasurde @goneri Any idea why `ansible-test-cloud-integration-vmware-rest-python38` keeps running into `POST_FAILURE`?

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
> @Akasurde @goneri Any idea why `ansible-test-cloud-integration-vmware-rest-python38` keeps running into `POST_FAILURE`?

https://github.com/ansible/zuul-config/commit/0d321ce088799069378087de9ff2ee1a5f053c1a should help :crossed_fingers:.

**Comment by mariolenz** [comment]
Thanks @goneri, ansible/zuul-config#402 helped!

**Pull request merged**
