### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by nicolastalvasson**
Depends-On: https://github.com/ansible-collections/vmware.vmware_rest/pull/107

##### SUMMARY
correct the retrieve name.

##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME
README.md

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by Akasurde** [comment]
@nicolastalvasson Thanks for the fix. There are more occurrences of `community.vmware_rest` in README.md as well. Could you please fix those as well? Thanks.

**Comment by goneri** [comment]
Thanks @nicolastalvasson!

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Pull request merged**
