### PR TITLE
Cherry pick all the changes from Release 3.0.1 (#489)

### PR DESCRIPTION
**Pull request by bardielle**
Release 3.0.1

Release 3.0.1

Reviewed-by: Mario Lenz <m@riolenz.de>
Reviewed-by: GomathiselviS
Reviewed-by: Alina Buzachis

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Review by alinabuzachis — APPROVED** [review]

**Comment by bardielle** [comment]
@alinabuzachis do you know how I can skip the changelog here?  I don't think we need to add a changelog for a cherry-picking PR but I might wrong...

**Comment by alinabuzachis** [comment]
> @alinabuzachis do you know how I can skip the changelog here? I don't think we need to add a changelog for a cherry-picking PR but I might be wrong...

@bardielle  This PR should fix https://github.com/ansible-collections/vmware.vmware_rest/pull/494

**Comment by bardielle** [comment]
recheck

**Comment by bardielle** [comment]
recheck

**Comment by bardielle** [comment]
recheck

**Pull request merged**
