### PR TITLE
bump auto-generated modules

### PR DESCRIPTION
**Pull request by goneri**
Depends-On: https://github.com/ansible/ansible/pull/73540
Depends-On: https://github.com/ansible/ansible/pull/73539
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/780

The modules are autogenerated by:
https://github.com/ansible-collections/vmware_rest_code_generator
version: 530b7746f35a16e1fdf1025d81e005bb07641ce2

### CODE REVIEW

**Comment by goneri** [comment]
recheck

**Comment by Akasurde** [comment]
CI fixed via https://github.com/ansible/ansible/pull/73322

**Comment by Akasurde** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Pull request closed without merging**
