### PR TITLE
Remove support for ansible-core 2.14

### PR DESCRIPTION
**Pull request by bardielle**
##### SUMMARY
This will be a major release that removing the support for ansible core 2.14 since the EOL. 

##### ISSUE TYPE
-Breaking changes

### CODE REVIEW

**Comment by bardielle** [comment]
recheck

**Comment by bardielle** [comment]
recheck

**Review by mikemorency — APPROVED** [review]

**Review by mariolenz — COMMENTED** [review]
Since this is a breaking change, it will make it impossible to do a bugfix or minor release if needed. Or you need to remember undoing this before you do. So I suggest to postpone this until you're ready to do a new major release. (Please try to synchronize with the community package there. Remember?)

Personally, I like to create milestones and issues where I collect breaking changes that I want to implement in the next major release (see [here](https://github.com/ansible-collections/community.vmware/milestone/16) for an example) so I don't forget. Maybe this would help here, too.

**Comment by bardielle** [comment]
recheck

**Review by mariolenz — CHANGES_REQUESTED** [review]
I've removed the `mergeit` label because I don't understand this PR.

1. This PR drops the `action_groups` which I think is a serious regression
2. There's #511 that still requires 2.14

I suggest to close this PR, update #511 to require 2.15 and regenerate everything.

**Comment by mikemorency** [comment]
https://github.com/ansible-collections/vmware.vmware_rest/pull/511 is still a draft (ci is making me cry)
The plan is to merge this, then make the final 4.0.0 release

Ill re-add the action_groups, it wasnt intended to leave them out

**Pull request merged**
