### PR TITLE
Run GHA job to validate changelog only for PRs

### PR DESCRIPTION
**Pull request by mariolenz**
Run GHA job to validate changelog only for PRs.

### CODE REVIEW

**Comment by mariolenz** [comment]
recheck

**Comment by mariolenz** [comment]
recheck

**Comment by mariolenz** [comment]
@webknjaz Does this look OK to you? As I've said, I'm not very good at GHA.

**Comment by webknjaz** [comment]
@mariolenz this'll do. Although, if you're going to use it in the branch protection in the future, remember to check out reusable workflows as that may simplify gating.

**Comment by mariolenz** [comment]
Thanks @webknjaz! I'll try to have a look at reusable workflows :-)

**Pull request merged**
