### PR TITLE
CI - linters and changelog github actions workflow

### PR DESCRIPTION
**Pull request by abikouo**
CI migration from zuul to GHA

### CODE REVIEW

**Comment by abikouo** [comment]
recheck

**Review by alinabuzachis — APPROVED** [review]

**Comment by mariolenz** [comment]
There already is a test for a changelog: #406 / #433

For the linter test, I don't understand why you use `abikouo/github_actions/.github/workflows/tox-linters.yml@tox_linters`. It looks like there is one in [ansible-network/github_actions](https://github.com/ansible-network/github_actions). I think it would be better to use this one.

Actually, I think it would be best to have linting in [ansible-collections/collection_template](https://github.com/ansible-collections/collection_template) and we could just copy it it to this collection. Maybe you should create a PR there to implement a default linting CI workflow ;-)

**Comment by abikouo** [comment]
> There already is a test for a changelog: #406 / #433
> 
> For the linter test, I don't understand why you use `abikouo/github_actions/.github/workflows/tox-linters.yml@tox_linters`. It looks like there is one in [ansible-network/github_actions](https://github.com/ansible-network/github_actions). I think it would be better to use this one.
> 
> Actually, I think it would be best to have linting in [ansible-collections/collection_template](https://github.com/ansible-collections/collection_template) and we could just copy it it to this collection. Maybe you should create a PR there to implement a default linting CI workflow ;-)

@mariolenz this PR needs some updates. 
Indeed, the changelog workflow added here is not valid anymore as there is already one.
And yes we should not reference action from personal repos.

**Review by mariolenz — APPROVED** [review]
I'm no GHA expert but as far as I can see this LGTM.

@alinabuzachis What do you think?

**Review by alinabuzachis — APPROVED** [review]

**Comment by mariolenz** [comment]
> Depends-On: [ansible/ansible-zuul-jobs#1789](https://github.com/ansible/ansible-zuul-jobs/pull/1789)

I've removed this. I think it makes more sense if removing those tests from Zuul should depend on implementing them here in the collection instead of the other way around ;-)

**Comment by mariolenz** [comment]
regate

**Comment by mariolenz** [comment]
Cool, we now also have a GHA linting workflow. Thanks @abikouo!

**Pull request merged**
