### PR TITLE
The module_utils/vmware.py is licensed under BSD license

### PR DESCRIPTION
**Pull request by goneri**

### CODE REVIEW

**Comment by mariolenz** [comment]
Why change the license to BSD? IANAL but it might be difficult if this collection uses several software licenses.

**Comment by goneri** [comment]
> Why change the license to BSD? IANAL but it might be difficult if this collection uses several software licenses.

It's a community policy: https://docs.ansible.com/ansible/latest/dev_guide/developing_module_utilities.html#standard-module-utilities

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by mariolenz** [comment]
> It's a community policy: https://docs.ansible.com/ansible/latest/dev_guide/developing_module_utilities.html#standard-module-utilities

Thanks @goneri, I didn't know this policy yet.

**Pull request merged**
