### PR TITLE
[WIP] Fix CI

### PR DESCRIPTION
**Pull request by mariolenz**
##### SUMMARY
Fix CI

##### ISSUE TYPE
- Bugfix Pull Request

##### ADDITIONAL INFORMATION
#503
#505
#506

### CODE REVIEW

**Comment by alinabuzachis** [comment]
recheck

**Comment by mariolenz** [comment]
@alinabuzachis @mikemorency It looks like the CI has been fixed by ansible/ansible-zuul-jobs#1883 so I wonder if this PR is really useful. Should we close it, or do you think this would be helpful?

I'm not sure, but tend to the opinion that it should be closed because the CI issue looks fixed and I don't see any other benefit.

**Comment by mikemorency** [comment]
Yes, i think we should close it

**Comment by mariolenz** [comment]
Closing as per above comment.

**Pull request closed without merging**
