### PR TITLE
content_library: add an example to identify a lib based on name

### PR DESCRIPTION
**Pull request by goneri**
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/1544
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/1545

### CODE REVIEW

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
regate

**Comment by mariolenz** [comment]
regate

**Comment by mariolenz** [comment]
regate

**Pull request merged**
