### PR TITLE
Fix sanity tests for 2.15

### LINKED ISSUE #355: Collection CI related actions needed
##### SUMMARY
Relates to https://github.com/ansible-collections/news-for-maintainers/issues/24.

It's been detected that this repository contains `ignore-2.14.txt` file but not `ignore-2.15.txt` file.

Actions needed:
- Copy `tests/sanity/ignore-2.14.txt` to `tests/sanity/ignore-2.15.txt` otherwise the CI will get failing.
- If it's not done yet, add the `stable-2.15` branch to your CI workflow files. If you use GitHub actions, see the content of `.github/workflows` or, if you use Azure Pipelines, `community.postgresql/.azure-pipelines/azure-pipelines.yml`. If not added, this will violate the [Collection Requirements](https://github.com/ansible-collections/overview/blob/main/collection_requirements.rst#ci-testing) for collections included in the Ansible package.
- Subscribe to and track the [news-for-maintainers](https://github.com/ansible-collections/news-for-maintainers) repository if you're not subscribed yet.
- If it's not relevant for this repo, just close the issue.

To read more about the topic, see the [Ignores](https://docs.ansible.com/ansible/devel/dev_guide/testing/sanity/ignores.html) guide.

To read more about the context, see the [announcement](https://github.com/ansible-collections/news-for-maintainers/issues/24).

Thank you!

### PR DESCRIPTION
**Pull request by mariolenz**
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/1639

##### SUMMARY
Fix sanity tests for 2.15

Fixes #355

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
vcenter_vm_guest_customization
appliance_infraprofile_configs

### CODE REVIEW

**Comment by goneri** [comment]
This file is autogenerated with https://github.com/ansible-collections/vmware_rest_code_generator. I prepare a fix that include your change.

**Comment by goneri** [comment]
recheck

**Comment by mariolenz** [comment]
> This file is autogenerated with https://github.com/ansible-collections/vmware_rest_code_generator. I prepare a fix that include your change.

Sorry, I thought you would manage those files here manually. Just close this PR. I would have closed it myself, but since you've issued a `recheck` it looks like you're using this PR to test something and I didn't want to break this.

BTW: Is this repo _completely_ autogenerated with vmware_rest_code_generator? There's _no_ file managed manually, everything is generated?

**Comment by mariolenz** [comment]
@goneri Do you still want to use this PR to test something or can we close it?

**Comment by goneri** [comment]
recheck

**Comment by mariolenz** [comment]
recheck

**Pull request closed without merging**
